{% set version = "1.16.11" %}

package:
    name: coinor-clp
    version: !!str {{ version }}

source:
    fn: Clp-{{ version }}.tgz
    url: https://www.coin-or.org/download/source/Clp/Clp-{{ version }}.tgz
    sha256: b525451423a9a09a043e6a13d9436e13e3ee7a7049f558ad41a110742fa65f39

build:
    number: 0

test:
    commands:
        - test -f ${PREFIX}/lib/libClp.so # [linux]


